config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :new, :create, :show, :edit, :update]
  resources :cat_rental_requests, only: [:new, :create, :show] do
    member do
      post 'approve'
      post 'deny'
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord

    COLORS = %w(White Black Ginger Blue/Grey Cream Brown Cinnamon Fawn)
    SEX = %w(M F)

    include ActionView::Helpers::DateHelper
    validates :color, inclusion: COLORS, presence: true
    validates :sex, inclusion: SEX, presence: true
    validates :birth_date, :name, :description, presence: true
    has_many :cat_rental_requests, dependent: :destroy

    #COLORS = ["white", "black", "ginger", "blue/grey", "cream", "brown", "cinnamon", "fawn"]
    #SEX = ["M","F"]

    def age
        time_ago_in_words(birth_date)
    end

end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord

    STATUS = %w(PENDING APPROVED DENIED)

    validates :cat_id, :start_date, :end_date, :status, presence: true
    validates :status, inclusion: STATUS, presence: true
    belongs_to :cat
    validate :does_not_overlap_approved_request

    def overlapping_requests
        #A cat rental request starting on 02/25/17 and ending on 02/27/17.
        #There is a overlap if another cat rental also starts on the same day (02/25/17).
        #There is a overlap if another cat rental request starts on the return day (02/27/17).
        #There is a overlap if another cat rental request starts between the start and end dates (02/26/17).
        #Find cases where there is no overlap then negate it
        #Start point of B comes after end point of A. B(start) > A(end)
        #Start point of A comes after end point of B. A(start) > B(end)
        #So there is not overlap when B(start) > A(end) || A(start) > B(end)
        #There is overlap when !(B(start) > A(end) || A(start) > B(end))
        #Or !(B(start) > A(end)) && !(A(start) > B(end))
        CatRentalRequest
            .where.not(id: self.id) #excludes self
            .where(cat_id: cat_id)
            .where(<<-SQL, start_date: start_date, end_date: end_date)
                NOT((start_date > :end_date) OR (:start_date > end_date))
            SQL
    end

    def overlapping_approved_requests
        overlapping_requests.where(status: 'APPROVED')
    end

    def does_not_overlap_approved_request
       if overlapping_pending_requests.exists?
        errors[:base] << 'Request overlaps with existing approved request'
       end
    end

    def overlapping_pending_requests
        overlapping_requests.where(status: 'PENDING')
    end

    def approve!
        CatRentalRequest.transaction do
            self.status = 'APPROVED'
            self.save!
            overlapping_pending_requests.update_all(status: 'DENIED')
        end
    end

    def deny!
        CatRentalRequest.transaction do
            self.status = 'DENIED'
            self.save!
        end
    end

    def pending?
        self.status == 'PENDING'
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

    def new
        render :new
    end

    def create
        @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
        if @cat_rental_request.save
            redirect_to cat_url(@cat_rental_request.cat)
        else
            render :new
        end
    end

    private_methods

    def cat_rental_request_params
        params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
    end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find_by(id: params[:id])
        @rental_requests = @cat.cat_rental_requests.order(:start_date)
        if @cat
            render :show
        else
            redirect_to cats_url
        end
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            # show user the cat show page
            redirect_to cat_url(@cat)
        else
            # show user the new cat form
            render :new
        end
    end

    def edit
        @cat = Cat.find_by(id: params[:id])
        render :edit
    end

    def update
        @cat = Cat.find_by(id: params[:id])

        if @cat.update_attributes(cat_params)
            redirect_to cat_url(@cat)
        else
            render :edit
        end
    end

    private
    
    def cat_params
        params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Create a Rental Request</h1>

<form action= <%= cat_rental_requests_url %> method="post">

    <label for="cat_rental_requests_url">Cat</label>
    <select name="cat_rental_request[cat_id]" id="cat_rental_request_cat_id">
        <option disabled selected="true">-- Select a Cat --</option>
        <% Cat.all.each do |cat| %>
            <option value="<%= cat.id %>">
                <%= cat.name %>
            </option>
        <% end %>
    </select>

    <br>

    <label for="cat_rental_request_start_date">Start date</label>
    <input 
        type="date" 
        id="cat_rental_request_start_date"
        name="cat_rental_request[start_date]" 
        value=<%= Date.today %>>

    <br>

    <label for="cat_rental_request_end_date">End date</label>
    <input 
        type="date" 
        id="cat_rental_request_end_date" 
        name="cat_rental_request[end_date]"
        value=<%= Date.tomorrow %>>

    <br><br>

    <input type="submit" value="Create Rental Request">

</form>

app/views/cats/_form.html.erb
<% if cat.persisted? %>
    <% action_url = cat_url(cat) %>
<% else %>
    <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">
    <% if cat.persisted? %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <label for="name">Name</label>
    <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">

    <br>

    <label for="birth_date">Birth Date</label>
    <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

    <br>

    <label for="color">Color</label>
    <select id="color" name="cat[color]">
        <option disabled <%= cat.color ? "" : "selected" %>>-- select a color --</option>
        <option value="White" <%= cat.color == "White" ? "selected" : "" %> >White</option>
        <option value="Black" <%= cat.color == "Black" ? "selected" : "" %> >Black</option>
        <option value="Ginger" <%= cat.color == "Ginger" ? "selected" : "" %> >Ginger</option>
        <option value="Blue/Grey" <%= cat.color == "Blue/Grey" ? "selected" : "" %> >Blue/Grey</option>
        <option value="Cream" <%= cat.color == "Cream" ? "selected" : "" %> >Cream</option>
        <option value="Brown" <%= cat.color == "Brown" ? "selected" : "" %> >Brown</option>
        <option value="Cinnamon" <%= cat.color == "Cinnamon" ? "selected" : "" %> >Cinnamon</option>
        <option value="Fawn" <%= cat.color == "Fawn" ? "selected" : "" %> >Fawn</option>
    </select>

    <br>

    <label for="sex">Sex</label>
    <select id="sex" name="cat[sex]">
        <option disabled <%= cat.sex ? "" : "selected" %>>-- select a sex --</option>
        <option value="M" <%= cat.sex == "M" ? "selected" : "" %> >M</option>
        <option value="F" <%= cat.sex == "F" ? "selected" : "" %> >F</option>
    </select>

    <br>

    <label for="description">Description</label>
    <textarea id="description" name="cat[description]"></textarea>
        <%= cat.description %>
    <br><br>

    <input type="submit" value="<%= (action == :edit) ? 'update cat' : 'add cat' %>">
</form>

app/views/cats/edit.html.erb
<h1>Edit <%= @cat.name %></h1>

<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1>99 Cats</h1>

<ul>
    <% @cats.each do |cat| %>
    <li><%= link_to cat.name, cat %></li>
    <% end %>
</ul>

app/views/cats/new.html.erb
<h1>Add cat!</h1>

<%= render 'form', action: :new, cat: @cat %>

app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="4"><%= @cat.name %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>age</td>
            <td>birth date</td>
            <td>color</td>
            <td>sex</td>
            <td>description</td>
        </tr>
        <tr>
            <td><%= @cat.age %></td>
            <td><%= @cat.birth_date %></td>
            <td><%= @cat.color %></td>
            <td><%= @cat.sex %></td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>
</table>

<h3>Rental Requests for <%= @cat.name %></h2>
<ol>
    <% @rental_requests.each do |request| %>
    <li>Start Date: <%= request.start_date %> End Date: <%= request.end_date %></li>
        <% if request.status == 'PENDING' %>
            <%= button_to "Approve", approve_cat_rental_request_url %>
            <%= button_to "Deny", deny_cat_rental_request_url %>
        <% end %>
    <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinenineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>